## Prompt
format = """$nix_shell$directory$aws$all$package$fill$vcsh$git_commit$git_state$git_metrics$git_status$git_branch
$cmd_duration$jobs$battery$time$status$shell$custom$memory_usage$character"""
# add_newline = true

[cmd_duration]
show_notifications = true
format = "[$duration]($style) "

[character]
success_symbol = "[âµ](bright-red)[âµ](bright-blue)[âµ](bright-cyan)"
error_symbol = "[âµâµâµ](red)"
# success_symbol = "[âœ](bold green)"
# error_symbol = "[âœ](bold red)"
# vicmd_symbol = "[â†–](bold purple)"
vicmd_symbol = "[âŒœ](bold purple)"

[fill]
symbol = " "

[line_break]
disabled = true

## System

[battery]
format = "[$symbol $percentage]($style) "

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 20
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 35
style = "bold yellow"

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style) "
style = "fg:#999cb2 bg:#2d2f40 bold"
read_only = " ï€£ "
read_only_style = "fg:black bg:red"
truncation_length=1

# [directory]
# format = "[$path]($style)[$lock_symbol]($lock_style) "
# truncation_length=2
# fish_style_pwd_dir_length=3
# truncation_symbol = "â€¦/"

[env_var]
format = "ğŸ‹ [$env_value]($style) "
variable = "DOCKER_IMG_VERSION"
style = "yellow bold dimmed"

[memory_usage]
disabled = false
threshold = 70
symbol = "ğŸ"
style = "bold dimmed red"
format = "$symbol [${ram_pct}( | ${swap})]($style) "

## Lang

[java]
disabled = true

[nodejs]
format = "Â· [$symbol($version )]($style) "

[python]
format = 'Â· [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[rust]
style = "bold #d2470a"
format = "Â· [$symbol($version )]($style) "

## Tools

[aws]
style = "bold #bb7445"
# displayed_items = "profile"
format = "Â· [$symbol$profile]($style) "
[aws.region_aliases]
eu-west-1 = "ir"
eu-west-3 = "fr"

[git_branch]
format = " [$symbol$branch]($style) "

[kubernetes]
format = "Â· [â˜¸ $context \\($namespace\\)](dimmed #305ebc) "
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

[nix_shell]
symbol = "â„"
impure_msg = "[ â„â£ ](fg:white bg:red bold)"
pure_msg = "[ â„â£ ](fg:white bg:blue bold)"
format = '[$state]($style)'
# style = "fg:#7e819b bg:#50398b bold"

## Other

[package]
format = "Â· [$symbol$version]($style) "

## Custom

[custom]

[custom.tab]
command = "tab --starship"
when = "tab --starship"
style = "bold blue"
format = " â‡¥ [$symbol$output]($style) "

[custom.env]
command = 'echo $env'  # shows output of command
files = [".envrc"]
when = """ [[ -n "$env" ]] """
format = "[$output]($style) "

[custom.nixshell]
command = """ if [ -n "$NIX_SHELL_PKG" ] ; then echo "trying: $NIX_SHELL_PKG" ; fi """
when = """ [[ "$name" == "nix-shell" || "$name" == "nix shell" ]] """
format = "ğŸš[$output]($style) "
